import { useState, useEffect } from 'react';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from './ui/select';
import { Button } from './ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from './ui/dialog';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { projectsApi } from '@/services/api';
import { Plus } from 'lucide-react';
import { toast } from 'sonner';

interface Project {
  _id: string;
  name: string;
  description?: string;
  keywords: string;
}

interface ProjectSelectorProps {
  value?: string;
  onValueChange: (value: string) => void;
  onProjectCreated?: () => void;
}

export function ProjectSelector({ value, onValueChange, onProjectCreated }: ProjectSelectorProps) {
  const [projects, setProjects] = useState<Project[]>([]);
  const [loading, setLoading] = useState(true);
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [newProject, setNewProject] = useState({
    name: '',
    description: '',
    keywords: '',
  });
  const [creating, setCreating] = useState(false);

  useEffect(() => {
    fetchProjects();
  }, []);

  const fetchProjects = async () => {
    try {
      const response = await projectsApi.getAll();
      setProjects(response.data.projects || []);
    } catch (error) {
      console.error('Error fetching projects:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleValueChange = (selectedValue: string) => {
    if (selectedValue === '__create_new__') {
      setCreateDialogOpen(true);
    } else {
      onValueChange(selectedValue);
    }
  };

  const handleCreateProject = async () => {
    if (!newProject.name) {
      toast.error('Project name is required');
      return;
    }

    setCreating(true);
    try {
      // Only send the name - backend will generate description and keywords
      const response = await projectsApi.create({ name: newProject.name });
      await fetchProjects();
      setCreateDialogOpen(false);
      setNewProject({ name: '', description: '', keywords: '' });
      // Set the newly created project as selected
      onValueChange(response.data.project.name);
      toast.success('Project created successfully!');
      if (onProjectCreated) {
        onProjectCreated();
      }
    } catch (error: any) {
      console.error('Error creating project:', error);
      toast.error(error.response?.data?.error || 'Failed to create project');
    } finally {
      setCreating(false);
    }
  };

  if (loading) {
    return <div className="text-sm text-muted-foreground">Loading projects...</div>;
  }

  return (
    <>
      <div className="flex gap-2">
        <Select value={value} onValueChange={handleValueChange}>
          <SelectTrigger className="w-full">
            <SelectValue placeholder="Select a project" />
          </SelectTrigger>
          <SelectContent>
            {projects.map((project) => (
              <SelectItem key={project._id} value={project.name}>
                {project.name}
              </SelectItem>
            ))}
            <SelectItem value="__create_new__" className="text-primary font-semibold">
              <div className="flex items-center gap-2">
                <Plus className="h-4 w-4 text-green-500" />
                Create New Project
              </div>
            </SelectItem>
          </SelectContent>
        </Select>
      </div>

      <Dialog open={createDialogOpen} onOpenChange={setCreateDialogOpen}>
        <DialogContent className="sm:max-w-[450px] bg-white">
          <DialogHeader>
            <DialogTitle className="text-xl font-semibold">Create New Project</DialogTitle>
            <DialogDescription className="text-sm text-muted-foreground">
              AI will automatically generate description and keywords based on the project name and knowledge documents.
            </DialogDescription>
          </DialogHeader>
          
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="name" className="text-sm font-medium">
                Project Name <span className="text-destructive">*</span>
              </Label>
              <Input
                id="name"
                value={newProject.name}
                onChange={(e) => setNewProject({ ...newProject, name: e.target.value })}
                placeholder="e.g., Denowatts"
                className="h-10"
              />
              <p className="text-xs text-muted-foreground">
                Description and keywords will be automatically generated by AI.
              </p>
            </div>
          </div>
          
          <DialogFooter className="gap-2 sm:gap-0">
            <Button 
              variant="outline" 
              onClick={() => {
                setCreateDialogOpen(false);
                setNewProject({ name: '', description: '', keywords: '' });
              }}
              disabled={creating}
            >
              Cancel
            </Button>
            <Button 
              onClick={handleCreateProject} 
              disabled={creating || !newProject.name.trim()}
              className="min-w-[120px]"
            >
              {creating ? 'Creating...' : 'Create Project'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}

